### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by ttxtea** [chmln/i3-auto-layout#1]
This is wonderful i3 extension. When freshly installed it worked for a while. Then sometimes it stops. At frist `i3-msg restart` and `i3-msg reload` enabled the auto-layout again. At the moment it does not. Was wondering if there is a debug mode, or a general strategy on how to debug it. `exec_always --no-startup-id i3-auto-layout` is in `.i3/config`. Its on i3 version 4.13.

**Comment by chmln** [comment]
@ttxtea I recommend running it inside a systemd user service which autorestarts. Crashes are rare, just make sure you're running the latest version from master. 

In any case I'll see if I can get better output when errors happen.

**Comment by chmln** [comment]
@ttxtea should be much improved now, with proper output when errors happen.
