### ISSUE TITLE
i3-auto-layout not working

### ISSUE THREAD

**Issue by muralikodali** [chmln/i3-auto-layout#6]
for some time i3-auto-layout is not working.

it is not even showing up in running processes.

**Comment by the-shank** [comment]
I am having this issue as well.

Installed `i3-auto-layout` via cargo.
And I have the following line in my i3config

```
exec_always --no-startup-id ~/.cargo/bin/i3-auto-layout
```

**Comment by rengare** [comment]
@the-shank @muralikodali I fixed the issue by upgrading one of the dependencies.
In the mean time you can go to my repo and compile it manually (https://github.com/rengare/i3-auto-layout)

**Comment by the-shank** [comment]
> @the-shank @muralikodali I fixed the issue by upgrading one of the dependencies. In the mean time you can go to my repo and compile it manually (https://github.com/rengare/i3-auto-layout)

Thanks, will do !

**Comment by muralikodali** [comment]
@the-shank thanks for your suggestion.

i have compiled the binary after cloning from https://github.com/rengare/i3-auto-layout.
it is working well.
